// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ_vZW7TG8n2i2FkwDLbsxBNtHjaCG5mg',
    appId: '1:10566858867:web:c071e1e2c36152618e1206',
    messagingSenderId: '10566858867',
    projectId: 'digital-menu-a7faf',
    authDomain: 'digital-menu-a7faf.firebaseapp.com',
    storageBucket: 'digital-menu-a7faf.firebasestorage.app',
    measurementId: 'G-0E1PQMQZ63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbe0qJwTwg8PBV4PACjtPnlD5URO9vJsI',
    appId: '1:10566858867:android:6c38c721c4f85eaa8e1206',
    messagingSenderId: '10566858867',
    projectId: 'digital-menu-a7faf',
    storageBucket: 'digital-menu-a7faf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_56v2Voi4TQa1k7tWPd11gNUcuCqv7OM',
    appId: '1:10566858867:ios:639b8797d7e429af8e1206',
    messagingSenderId: '10566858867',
    projectId: 'digital-menu-a7faf',
    storageBucket: 'digital-menu-a7faf.firebasestorage.app',
    iosBundleId: 'com.example.projectFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_56v2Voi4TQa1k7tWPd11gNUcuCqv7OM',
    appId: '1:10566858867:ios:639b8797d7e429af8e1206',
    messagingSenderId: '10566858867',
    projectId: 'digital-menu-a7faf',
    storageBucket: 'digital-menu-a7faf.firebasestorage.app',
    iosBundleId: 'com.example.projectFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ_vZW7TG8n2i2FkwDLbsxBNtHjaCG5mg',
    appId: '1:10566858867:web:bacba00c918bacfe8e1206',
    messagingSenderId: '10566858867',
    projectId: 'digital-menu-a7faf',
    authDomain: 'digital-menu-a7faf.firebaseapp.com',
    storageBucket: 'digital-menu-a7faf.firebasestorage.app',
    measurementId: 'G-75WDN0Q0N6',
  );
}
